# Generated by Django 4.0.2 on 2022-07-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='footnote',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='index',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
