# Generated by Django 4.0.2 on 2022-03-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
