# Generated by Django 4.0.2 on 2022-07-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_topic_footnote_alter_topic_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='footnote',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
