# Generated by Django 4.0.2 on 2022-12-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_topic_footnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_live',
            new_name='is_approved',
        ),
    ]
