# Generated by Django 4.0.2 on 2022-04-22 08:32

import Excelegal.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_topic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Excelegal.helpers.UploadTo('uploads'), validators=[Excelegal.helpers.validate_image]),
        ),
    ]
