# Generated by Django 4.0.2 on 2022-04-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_ids',
            field=models.TextField(default='[]'),
        ),
    ]
