# Generated by Django 4.0.2 on 2022-04-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='course',
            new_name='courses',
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='question',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Subjects'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subjects',
            field=models.ManyToManyField(to='quiz.Subjects'),
        ),
    ]
