# Generated by Django 4.0.2 on 2022-04-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_question_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattemptedquestion',
            name='user_quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.userattemptedquiz'),
        ),
        migrations.AlterField(
            model_name='userattemptedquiz',
            name='attempted_questions',
            field=models.TextField(default='[]'),
        ),
    ]
