# Generated by Django 4.0.2 on 2022-04-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('quiz', '0002_subjects_rename_course_quiz_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.AddField(
            model_name='question',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='quiz.Subjects'),
        ),
    ]
