# Generated by Django 4.0.2 on 2022-04-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subjects',
            field=models.ManyToManyField(to='quiz.Subjects'),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question'),
        ),
    ]
