# Generated by Django 4.0.2 on 2022-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
