# Generated by Django 4.0.2 on 2022-04-22 07:58

import Excelegal.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Excelegal.helpers.UploadTo('uploads'), validators=[Excelegal.helpers.validate_image]),
        ),
    ]
