# Generated by Django 4.0.2 on 2022-04-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserUpload',
        ),
    ]
