# Generated by Django 4.0.2 on 2022-03-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_created_at_user_from_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Admin'), (2, 'Mentor'), (1, 'Student')], null=True),
        ),
    ]
