# Generated by Django 4.0.2 on 2022-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Admin'), (2, 'Staff'), (1, 'Student')], default=1, null=True),
        ),
    ]
