# Generated by Django 4.0.2 on 2022-03-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
