# Generated by Django 4.0.2 on 2022-11-02 09:20

import Excelegal.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='action_link',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='action_title',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='category',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Excelegal.helpers.UploadTo('bulletin_images'), validators=[Excelegal.helpers.validate_image]),
        ),
    ]
